version: '3.6'

services:

  postgres:
    build:
      context: .
      dockerfile: db/Dockerfile
    env_file: dev.env
    ports:
      - "5432:5432"
    networks:
      - titus
    volumes:
      - ../pgdata:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - titus

  fastify-api:
    build:
      context: ../
      dockerfile: $PWD/docker/api/Dockerfile
    env_file: dev.env
    depends_on:
      - postgres
      - redis
    networks:
      - titus
    ports:
      - "5000:5000"
    volumes:
      - ..:/titus
    environment:
      - PGHOST=postgres
      - PGPORT=5432

  adminer:
    image: adminer
    networks:
      - titus
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  s3:
    image: "mrister/fake-s3"
    ports:
    - "4569:4569"
    volumes:
    - /data/fake-s3

networks:
    titus:
